version: '3'
services:
    anaconda:
        build: .
        volumes:
            - ../:/workspace
            - ../data:/data
            - /mnt/sda1/Dropbox/data/secret:/secret
            - /mnt/sda1/Dropbox/data/private/youtube:/youtube
        ports:
            - "8888:8888"
